version: '3.8'

services:
  web:
    build: ../src
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ../src:/app
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: wms_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wms_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
